<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cartKineticSpeedProduct</name>
   <tag></tag>
   <elementGuidId>ad710d03-8f7b-4156-ad38-3fcb5d115efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;product-list-section&quot;]/div[1]/div/div[1]/div[2]/div/div[1]/ul/li/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
