<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wirelessBackupDetail</name>
   <tag></tag>
   <elementGuidId>2b3ead6c-c91a-4df9-a370-a4e1f5b93d00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;products-component&quot;]/div[3]/div[1]/div/div/div/div/div/div[2]/div/div/label/div[1]/p/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
